### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by steve02081504** [SCLeoX/sm-contract#4]
rt  
看了一遍清单，有以下几点：  
1. 玩法单一，像储酒、饮血之类的偏门玩法没有提及  
2. 清单过长，一些问题太过细节化  
3. 没有期望相互关系的选项  

建议以下几点：
1. 支持自行添加感兴趣（或厌恶）的玩法  
2. 填写问题后有”补充细节”选项，而不是弹出很长的表  
3. 丰富表格

**Comment by steve02081504** [comment]
@SCLeoX

**Comment by SCLeoX** [comment]
关于玩法不够多，其实是因为我对其他玩法并不了解。之前萌绫有另一个 Issue 就是关于补充新的玩法的（#3）。但是考虑到我完全不知道怎么写描述文本，后来我甚至建了一个 [Google Doc](https://docs.google.com/document/d/1yECvVzkidGhVtk5DerrA74gf4KMFbgQyqHoRufgLIeE/edit?usp=sharing) 想拉人帮忙写描述文本，但是就一个人来帮忙写了几句。所以，我现在不得不引用那句非常没有诚意的话了：“这是一个开源项目，你有主意你可以[自行添加](https://github.com/SCLeoX/sm-contract/tree/master/src/data)。”

关于补充细节。其实是这样的，事实证明，大家都懒得打字（所有被人交还给我的表格里面，偏好称呼都没有填写）。如果双方都愿意打字的话也没必要有这个表了。这个表在一定程度上起开脑洞的作用。如果需要补充细节的话，在另外的地方写上就好了。

**Comment by steve02081504** [comment]
好的
