### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by b1f6c1c4** [SCLeoX/sm-contract#5]
I’m interested in this project very much and really looking forward for it to become a community-driven, open, inclusive place for people to coordinate with others. However, a key factor for a successful open source project is to have an appropriate license. Without a license, others are unable to freely engage in the development and amelioration. Most importantly, we are NOT authorized to use, distribute, or modify your code anywhere outside Github.

I personally think that GNU Affero Public License, version 3 (AGPLv3) is a great fit for the project due to its strong restricting clauses limiting closed-source distribution. More information can be found [here](https://www.gnu.org/licenses/agpl-3.0.en.html).

**Comment by SCLeoX** [comment]
Thanks for your suggestion. I guess I will use the AGPL as you suggest.
