### ISSUE TITLE
[部署问题] 这个项目是使用什么构建的？

### ISSUE THREAD

**Issue by Dwscdv3** [SCLeoX/sm-contract#8]
minegeck.net 没了，我想自己 host 一份 sm-contract 却发现没有 packages.json

请问是忘记添加到仓库了，还是说这本来就不是一个 Node.js 项目呢？

**Comment by SCLeoX** [comment]
抱歉，这个可能我也构建不起来了。这个用的是自己写的依赖管理和构建系统。那套系统也早就已经运行不起来了。。。

**Comment by Dwscdv3** [comment]
嗯，好的。

为后来者推荐 [Misaka-0x447f/xp-oobe](https://github.com/Misaka-0x447f/xp-oobe)

请注意那个项目尚没有开源许可证，而且不支持 diff。
